export type Category = 'paper-writing' | 'desk-lighting' | 'desk-accents';
export interface Product {
  id: string;
  name: string;
  category: Category;
  price: number;
  image: string;
  alt: string;
  description: string;
  details: string[];
  badge?: string;
  featured?: boolean;
  position?: string;
}
export const categories: { id: Category; name: string; description: string; image: string }[] = [
  { id: 'paper-writing', name: 'Paper & writing', description: 'A place for the next good idea.', image: '/images/sketchbook.webp' },
  { id: 'desk-lighting', name: 'Desk lighting', description: 'A little light. A clearer perspective.', image: '/images/silver-lamp.webp' },
  { id: 'desk-accents', name: 'Desk accents', description: 'Small details that make it yours.', image: '/images/faux-plant.webp' },
];
export const products: Product[] = [
  { id: 'everyday-notebook', name: 'Everyday notebook', category: 'paper-writing', price: 1800, image: '/images/notebook.webp', alt: 'An open notebook beside glasses and a black journal', description: 'An uncomplicated companion for notes, small plans, and ideas worth keeping. A quiet place to start the day.', details: ['Lined notebook', 'Simple everyday format', 'A considered addition to your writing routine'], badge: 'Editor’s pick', featured: true },
  { id: 'pocket-journal', name: 'Pocket journal', category: 'paper-writing', price: 1600, image: '/images/journal.webp', alt: 'A dark closed journal with a pen on a soft gray tabletop', description: 'For the thought you want to catch before it slips away. Keep a little space for observations, lists, and fresh starts.', details: ['Compact journal', 'Minimal cover styling', 'Designed for everyday notes'], featured: true },
  { id: 'blank-sketchbook', name: 'Blank sketchbook', category: 'paper-writing', price: 2400, image: '/images/sketchbook.webp', alt: 'A blank spiral sketchbook on a creative workspace', description: 'Space to sketch, explore, and leave the first draft unfinished. A blank page with plenty of possibilities.', details: ['Blank-page sketchbook', 'Spiral-bound style', 'For doodles, drawings, and visual notes'], badge: 'New', featured: true },
  { id: 'writing-essentials', name: 'Writing essentials', category: 'paper-writing', price: 2200, image: '/images/pencils.webp', alt: 'Writing supplies arranged on a desk', description: 'A small collection for your daily notes and creative sessions. Bring a little intention to the tools you reach for.', details: ['Stationery assortment', 'For writing and everyday planning', 'A mix of everyday writing tools'] },
  { id: 'patterned-notebook-set', name: 'Patterned notebook set', category: 'paper-writing', price: 2800, image: '/images/notebook-set.webp', alt: 'Three patterned notebooks on a pink background', description: 'Give each project a space of its own. A playful mix of notebook covers for work, ideas, and everything in between.', details: ['Three-notebook collection', 'Mixed cover patterns', 'For separate projects and daily lists'], badge: 'New' },
  { id: 'quill-writing-set', name: 'Quill writing set', category: 'paper-writing', price: 3200, image: '/images/calligraphy.webp', alt: 'A white feather quill beside a green ink bottle on a dark surface', description: 'For slower notes and thoughtful words. An expressive writing set that brings a little ceremony to the page.', details: ['Feather quill and ink-bottle', 'An introduction to expressive writing', 'A decorative desk addition'] },
  { id: 'studio-task-lamp', name: 'Studio task lamp', category: 'desk-lighting', price: 6800, image: '/images/silver-lamp.webp', alt: 'A silver task lamp with a wooden arm beside books', description: 'A focused pool of light for your daily work. An understated silhouette with a warm, natural detail.', details: ['Task-lamp with adjustable-style arm', 'Silver and natural-wood styling', 'A decorative light for your workspace'], badge: 'Editor’s pick', featured: true, position: '35% center' },
  { id: 'industrial-table-lamp', name: 'Industrial table lamp', category: 'desk-lighting', price: 7400, image: '/images/pipe-lamp.webp', alt: 'An exposed-bulb lamp with a dark pipe base against a brick wall', description: 'A sculptural accent for a shelf or work corner. Simple lines, a dark finish, and a little character.', details: ['Pipe-base lighting', 'Exposed-bulb styling', 'A decorative light for your workspace'], featured: true },
  { id: 'ceramic-pen-cup', name: 'Ceramic pen cup', category: 'desk-accents', price: 1900, image: '/images/pen-cup.webp', alt: 'A ceramic cup holding pens and pencils on a desk', description: 'Keep your most-used writing tools close at hand. A cheerful accent for a desk that feels a little more organized.', details: ['Pen-cup', 'Soft ceramic-style finish', 'Writing tools shown for styling; not included'], featured: true },
  { id: 'faux-desk-plant', name: 'Faux desk plant', category: 'desk-accents', price: 2600, image: '/images/faux-plant.webp', alt: 'A leafy artificial plant in a white pot against a coral background', description: 'A little greenery for your workday, without another thing on the to-do list. Easy to place, easy to enjoy.', details: ['Artificial greenery', 'White pot styling', 'A decorative accent for a desk or shelf'], badge: 'Editor’s pick', featured: true },
  { id: 'succulent-planter', name: 'Succulent planter', category: 'desk-accents', price: 2100, image: '/images/bowl-planter.webp', alt: 'A green succulent displayed in a white pot', description: 'A small home for your favorite desk-side greenery. A simple shape that lets the plant take the spotlight.', details: ['Small planter', 'White ceramic-style finish', 'Plant shown for styling; not included'], badge: 'New', position: 'center bottom' },
  { id: 'ripple-planter', name: 'Ripple planter', category: 'desk-accents', price: 2900, image: '/images/ceramic-planter.webp', alt: 'A young green plant in a textured round planter', description: 'A little texture, a little green, and a calmer corner of the room. A decorative planter for a shelf or sunny desk.', details: ['Textured round-planter', 'Neutral natural styling', 'Plant shown for styling; not included'], featured: true },
  {"id": "daily-planner", "name": "Daily desk planner", "category": "paper-writing", "price": 2200, "image": "/images/daily-planner.webp", "alt": "A blank notepad resting on a desk", "description": "A clear place for today’s tasks, tomorrow’s plans, and the ideas that arrive in between.", "details": ["Open-page planning format", "Space for notes and daily priorities", "Easy to keep beside your keyboard"], "badge": "New"},
  {"id": "floral-notebook", "name": "Floral notebook", "category": "paper-writing", "price": 2000, "image": "/images/floral-notebook.webp", "alt": "A floral notebook with a decorative pen on a green surface", "description": "A little pattern for your daily pages. Keep your notes in a notebook with a cheerful botanical point of view.", "details": ["Floral cover styling", "For ideas, lists, and everyday notes", "A colorful addition to your desk"]},
  {"id": "blush-notebook", "name": "Blush notebook", "category": "paper-writing", "price": 1800, "image": "/images/blush-notebook.webp", "alt": "A pink notebook beside a matching pink pen", "description": "Soft color, fresh pages, and room for your next thought. An easy companion for a slower start to the day.", "details": ["Soft pink cover styling", "Everyday writing format", "Pen pictured for styling"]},
  {"id": "travel-journal", "name": "Map journal", "category": "paper-writing", "price": 2400, "image": "/images/travel-journal.webp", "alt": "An open notebook on top of a world map", "description": "For routes, reflections, and ideas that go a little further. Keep a space for the places on your mind.", "details": ["Open-page journal format", "For reflections and travel notes", "Map pictured for styling"]},
  {"id": "fine-tip-pen", "name": "Fine-tip writing pen", "category": "paper-writing", "price": 1200, "image": "/images/fine-tip-pen.webp", "alt": "A close view of a fine-tipped writing pen", "description": "A simple tool for careful notes and little details. Keep a dependable writing companion close to your next blank page.", "details": ["Fine-tip styling", "For notes and everyday writing", "A minimal desk essential"]},
  {"id": "colored-pencils", "name": "Color pencil collection", "category": "paper-writing", "price": 1800, "image": "/images/colored-pencils.webp", "alt": "Newly sharpened colored pencils arranged together", "description": "Bring a little color to your thinking. A playful collection for sketches, visual notes, and a fresh perspective.", "details": ["A mix of colored pencils", "For sketching and creative notes", "Sharpened-point styling"], "badge": "New"},
  {"id": "marker-set", "name": "Color marker set", "category": "paper-writing", "price": 1600, "image": "/images/marker-set.webp", "alt": "A hand holding four colorful markers", "description": "For ideas that deserve a little emphasis. A colorful set to bring plans, sketches, and study notes into focus.", "details": ["Four-color marker collection", "For highlighting ideas and sketching", "Compact writing tools"]},
  {"id": "artist-brushes", "name": "Artist paintbrush", "category": "paper-writing", "price": 2200, "image": "/images/artist-brushes.webp", "alt": "A paintbrush making a white stroke on purple paper", "description": "Leave room for a creative pause. A brush for color studies, small experiments, and expressive marks.", "details": ["Single artist brush", "For painting and creative sessions", "An expressive desk-side collection"]},
  {"id": "wood-calendar", "name": "Wooden desk calendar", "category": "desk-accents", "price": 2800, "image": "/images/wood-calendar.webp", "alt": "A wooden calendar on a light background", "description": "A small daily ritual for your workspace. Natural texture and a simple date display bring a little intention to the morning.", "details": ["Wooden calendar styling", "A compact tabletop accent", "For a daily date-setting ritual"], "badge": "New"},
  {"id": "white-clock", "name": "White alarm clock", "category": "desk-accents", "price": 3200, "image": "/images/white-clock.webp", "alt": "A white alarm clock with a round face", "description": "Keep time in view with a clean, quiet silhouette. A light finishing touch for a shelf, bedside table, or work corner.", "details": ["Round clock face", "White finish styling", "Tabletop clock format"]},
  {"id": "gold-clock", "name": "Black & gold desk clock", "category": "desk-accents", "price": 4600, "image": "/images/gold-clock.webp", "alt": "A black and gold clock on a white table", "description": "A little contrast, a little warmth. A distinctive clock that gives your desk an elegant focal point.", "details": ["Black and gold styling", "Readable analog face", "For a desk or display shelf"]},
  {"id": "ceramic-mug", "name": "Everyday ceramic mug", "category": "desk-accents", "price": 1800, "image": "/images/ceramic-mug.webp", "alt": "A gray ceramic coffee mug", "description": "For the first coffee and the afternoon pause. An understated mug that feels at home beside your daily notes.", "details": ["Gray ceramic styling", "An everyday drinkware shape", "For your desk-side coffee ritual"], "badge": "New"},
  {"id": "enamel-mug", "name": "Blue enamel mug", "category": "desk-accents", "price": 2000, "image": "/images/enamel-mug.webp", "alt": "A blue kettle and tin mug against a blue background", "description": "A cheerful companion for your workday breaks. Classic enamel styling brings a little character to a familiar ritual.", "details": ["Blue enamel-style finish", "Classic tin-mug silhouette", "Kettle shown for styling; not included"]},
  {"id": "woven-coaster", "name": "Woven mug coaster", "category": "desk-accents", "price": 1400, "image": "/images/woven-coaster.webp", "alt": "A white mug with a coaster on a gray blanket", "description": "A small layer of texture beneath your favorite cup. A simple finishing touch for a thoughtful coffee corner.", "details": ["Textured coaster styling", "For a mug or small glass", "Mug shown for styling; not included"]},
  {"id": "cedar-candle", "name": "Cedar & moss candle", "category": "desk-accents", "price": 2400, "image": "/images/cedar-candle.webp", "alt": "A cedarwood and moss candle in a glass jar", "description": "Warm styling for your wind-down corner. A jar candle that adds a considered detail to a shelf or side table.", "details": ["Cedarwood and moss label styling", "Glass jar vessel", "Never leave a burning candle unattended"]},
  {"id": "wood-wick-candle", "name": "Wood-wick jar candle", "category": "desk-accents", "price": 2600, "image": "/images/wood-wick-candle.webp", "alt": "A candle in a glass jar with a wooden wick", "description": "A little warmth for a slower moment. A simple jar and wooden-wick detail make a cozy addition to your space.", "details": ["Wooden-wick styling", "Glass jar format", "Keep lit candles away from paper and fabrics"]},
  {"id": "wood-frame", "name": "Natural wood picture frame", "category": "desk-accents", "price": 2200, "image": "/images/wood-frame.webp", "alt": "A person hanging a natural wooden frame on a white wall", "description": "Make room for a favorite view. A natural frame for the photo, print, or small reminder you want to keep nearby.", "details": ["Natural wood frame styling", "For a print or photograph", "Artwork pictured for styling"]},
  {"id": "studio-headphones", "name": "Studio over-ear headphones", "category": "desk-accents", "price": 8900, "image": "/images/studio-headphones.webp", "alt": "Black over-ear headphones photographed in monochrome", "description": "For the soundtrack to your daily routine. An understated pair of headphones that belongs beside your favorite work tools.", "details": ["Over-ear silhouette", "Dark minimal styling", "A desk-side listening accessory"], "badge": "New"},
  {"id": "compact-keyboard", "name": "Compact desk keyboard", "category": "desk-accents", "price": 6400, "image": "/images/compact-keyboard.webp", "alt": "A minimal workstation with a keyboard", "description": "A clean starting point for the day’s work. A compact keyboard brings a little order to your everyday setup.", "details": ["Compact keyboard styling", "For a minimal workspace", "Other workstation accessories not included"]},
  {"id": "vintage-lamp", "name": "Vintage accent lamp", "category": "desk-lighting", "price": 7800, "image": "/images/vintage-lamp.webp", "alt": "A vintage lamp beside a houseplant", "description": "A familiar shape with a little character. Bring a warm visual accent to a reading corner, shelf, or work surface.", "details": ["Vintage lamp styling", "A decorative tabletop light", "Plant shown for styling; not included"], "badge": "New"},
];
export const productById = new Map(products.map(product => [product.id, product]));
export const categoryName = (id: Category) => categories.find(category => category.id === id)!.name;
export const formatMoney = (cents: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
